<a href="https://colab.research.google.com/github/2303A51240/AIML-2025BT17-18/blob/main/aiml1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:


import numpy as np

list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]


array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])


print(type(list1))
print(type(array1))


print(array1 * array2)


print(array1 / array2)


print(array1 ** 2)


result = array1 + array2
print("Addition of Two: array1 + array2 = ", result)


print(np.sin(array1))
print(np.log(array1))
print(np.log2(array1))
print(np.exp(array1))


<class 'list'>
<class 'numpy.ndarray'>
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]
Addition of Two: array1 + array2 =  [ 6  8 10 12]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
